### ISSUE TITLE
designTokensTable crushes 

### ISSUE THREAD

**Issue by yarinsa** [UX-and-I/storybook-design-token#140]
I am getting the following error:
![Screen Shot 2022-11-17 at 12 01 14](https://user-images.githubusercontent.com/44482362/202416503-be9046e7-9c20-49b9-8021-794a83952471.png)
 ```
SearchField.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'defaultText')
    at SearchField.js:34:32
    at handleInterpolation (index.js:3482:24)
    at serializeStyles3 (index.js:3597:15)
    at index.js:3805:24
    at index.js:2509:12
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateForwardRef (react-dom.development.js:17044:20)
    at beginWork (react-dom.development.js:19098:16)
```

I traced back and it seems like its expecting me to have theme.color.defaultText (which is not even storybook theme interface). 
Willing to help with the fix

**Comment by Sqrrl** [comment]
I'm having issues reproducing this. What Storybook version are you using?

**Comment by yarinsa** [comment]
6.5.12

**Comment by Sqrrl** [comment]
I ran into a similar issue recently. Seems to be related to https://github.com/storybookjs/storybook/issues/7914

**Comment by YoungElPaso** [comment]
https://github.com/UX-and-I/storybook-design-token/blob/0691993bab1047662a430f8e38c440b950e679e5/addon/src/components/TokenTable.tsx#L78

Uses this theme property too, which seems to be the problem. This also does look like a valid Storybook theme property:

https://github.com/storybookjs/storybook/blob/42fae30325bb7635e38689e8cc9ece3740d49746/code/lib/theming/src/base.ts#L39

Maybe not having that set in a custom theme is the issue?
