### ISSUE TITLE
issue with enabled feature buildStoriesJson

### ISSUE THREAD

**Issue by jamir0** [UX-and-I/storybook-design-token#161]
Hi
I've added `features: { buildStoriesJson: true }` into the `/.storybook/main.js` and after this receive an error during the build storybook:

```
WARN 🚨 Extraction error on stories/colors-constants.stories.mdx: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
WARN 🚨 Extraction error on stories/colors.stories.mdx: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
WARN 🚨 Extraction error on stories/fonts.stories.mdx: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
.../node_modules/@storybook/csf/dist/index.js:60
  return string.toLowerCase() // eslint-disable-next-line no-useless-escape
                ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
at sanitize (.../node_modules/@storybook/csf/dist/index.js:60:17)
    at sanitizeSafe (.../node_modules/@storybook/csf/dist/index.js:67:19)
    at toId (.../node_modules/@storybook/csf/dist/index.js:81:20)
    at .../node_modules/@storybook/csf-tools/dist/cjs/CsfFile.js:496:34
    at Array.reduce (<anonymous>)
    at CsfFile.parse (.../node_modules/@storybook/csf-tools/dist/cjs/CsfFile.js:490:31)
    at StoryIndexGenerator.extractStories (.../node_modules/@storybook/core-server/dist/cjs/utils/StoryIndexGenerator.js:127:11)
    at async Promise.all (index 22)
    at async Promise.all (index 0)
    at async StoryIndexGenerator.ensureExtracted (.../node_modules/@storybook/core-server/dist/cjs/utils/StoryIndexGenerator.js:103:13)
    at async StoryIndexGenerator.initialize (.../node_modules/@storybook/core-server/dist/cjs/utils/StoryIndexGenerator.js:97:5)
error Command failed with exit code 1.
```

Errors happen just in stories where the `storybook-design-token` add-on is used. Before changing the configuration, all stories work properly.
Does anybody have the same error or probably know how to fix it?

Thank you in advance for any help.

UPDATE:
I found a solution:
For stories with tokens, I specified `id` property for `Meta` manually. It fixed the issue.

**Comment by Sqrrl** [comment]
Thanks for reporting and good to hear that you found a solution. Closing this.
